title: Sheaft, le Blog
default_lang: fr
author:
  name: Sheaft
  email: 'contact@sheaft.com'
metadata:
  description: 'Recettes, trucs et astuces, et actualit√© autour de la consommation locale'
mainmenu:
  - text: Accueil
    url: page:accueil
  - text: Notre site
    url: https://www.sheaft.com/
  - text: Notre app
    url: https://app.sheaft.com/
copyright:
  text1: Sheaft
  year: 2021
  url: https://www.sheaft.com/
  text2: www.sheaft.com